config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items
  root 'items#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all.order("created_at DESC")
  end

  def new
    @item = Item.new
  end

  def show

  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:title, :description)
  end

  def find_item
    @item = Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :title, label: "Item" %>
  <%= f.input :description %>
  <%= f.button :submit%>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Checklist Item</h1>

<%= render 'form' %>

app/views/items/index.html.erb
<% @items.each do |item| %>
  <h2><%= link_to item.title, item %></h2>
  <p><%= item.description %></p>
<% end %>

<%= link_to "New Item", new_item_path %>

app/views/items/new.html.erb
<h1>New Checklist Item</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<h2><%= @item.title %></h2>
<p><%= @item.description %></p>

<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_item_path(@item) %>
<%= link_to "Destroy", item_path(@item), method: :delete, data: { confirm: "Are you sure?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Checklist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Checklist", root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% if current_user.present? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <%= link_to "New Item", new_item_path, class: "navbar-text navbar-link navbar-right" %>
      <% end %>
    </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>